### ISSUE TITLE
error loading bundled icecast2

### ISSUE THREAD

**Issue by spheras** [spheras/messic#126]
If the system doesn't have the libshout lib, the activator launch an error while trying to load the library and the starter doesn't continue loading.

**Comment by israbr** [comment]
I've just been hit by this. Googleing libshout lib in the meantime

**Comment by spheras** [comment]
do you mean upload the library to git???

**Comment by israbr** [comment]
Yessssss. Don't do that.

**Comment by spheras** [comment]
no in this case, specially with the new JNA implementation (because i don't need now a jni wrapper library, It works now directly with JNA).  This plugin requires that the system has the libshout library and icecast2 installed.

by the way, in other cases I don't know why you think this is like to kill a little and happy bunny with your own hands. We need to talk this other day, with a beer (and a coke)

**Comment by israbr** [comment]
My main issue is 42 minutes of cloning the project ^_^ but like you said, time to book one beer (and a coke) for that chat.
