### ISSUE TITLE
Suggest track number in different volumes: vol1: 101,102,... vol2: 201, 202.. vol3: 301, 302..

### ISSUE THREAD

**Issue by ruayrod** [spheras/messic#127]
In bad english ;) :
I would suggest that when taken as a reference track number in different volumes on the same disk, is renumbered as it has always done in these cases, ie, Volume 1: 101, 102, 103 ... to 199; Volume 2: 201, 202, 203 ... to 299; Volume 3: 301, 302, 303 .. to 399; and so on.

En español:
Quisiera sugerir que a la hora de tomar como referencia el número de pista en diferentes volúmenes del mismo disco, se renumeren como se ha hecho siempre en estos casos, es decir, volumen 1: 101, 102, 103... hasta 199; volumen 2: 201, 202, 203... hasta 299; volumen 3: 301, 302, 303.. hasta 399; y así sucesivamente.
Es una opinión personal, simplemente que me extraña ver en la biblioteca de archivos que hace messic, que el vol02, la primera canción empiece en el número, por ejemplo, 12 y no en el 1, y en el vol03 empiece en el 23, y no en el 1... creo que sería lo suyo.. pero ya digo que es una sugerencia.

**Comment by spheras** [comment]
hello @ruayrod .
Sorry, I don't understand well.
In my tests different volumes has different numeration, i.e.:
Vol1-> 
01-lkfsdlkfjds
02-sldkfjsldjf
Vol2->
01-sdlfkd
02-sdlfkfd

Really you can modify the track number and put whatever you prefer, but automatically it gives you that. What did you to get 12 for the track number of the first song of the second volume? Could you try and give us the steps to reproduce the problem?

**Comment by ruayrod** [comment]
Ok. It's an error in mp3 tags in one from my collection.

**Comment by spheras** [comment]
can we close this issue then?

**Comment by ruayrod** [comment]
Yes, closed.
