### ISSUE TITLE
New album cover

### ISSUE THREAD

**Issue by amvilardo** [spheras/messic#128]
Hi,

How can I upload a album cover?

Regards.

**Comment by spheras** [comment]
Hi @amvilardo!
It is very easy in fact: you only need to add the cover file with the rest of mp3 files. You can do this while creating/uploading the new album or just adding a new file (jpeg, png, whatever cover file) to an existing album.

Try it and tell me if its ok.

**Comment by amvilardo** [comment]
Perfect, thank you very much!!
Another question:
I would like to upload many mp3 files. 
Should I do it one by one to put the metadata or is there another way?

Regards.

**Comment by spheras** [comment]
Do you mean mp3 files from different authors/albums?  At the upload page you can select all the files you need to upload, but all of them will be contained in the same album...so the idea is to upload all the files of the same album. If you want some kind of mix album, you can upload different songs together at the same time, but you will lost probably the album and author información of each song.

**Comment by amvilardo** [comment]
Ok, Thanks!!!!
